# Generated by Django 5.0.6 on 2024-05-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_rename_funcionario_funcionarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionarios',
            old_name='nome',
            new_name='name',
        ),
    ]
